# Generated by Django 3.0.3 on 2020-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
